### ISSUE TITLE
Data structure

### ISSUE THREAD

**Issue by Samoulvann** [PNC-NODE-PROJECT/G20-NODE-PROJECT#7]
@him-hey 
[Dear,] teacher could you check my Data structure

**Comment by phanith12** [comment]
[STUDENT (1).docx](https://github.com/PNC-NODE-PROJECT/G20-NODE-PROJECT/files/8568836/STUDENT.1.docx)

**Comment by phanith12** [comment]
@him-hey 
Now I has already Data structure. I hope you can check as you free.
